security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        user_provider:
            entity:
                class: App\Entity\Usuario
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            lazy: true
            provider: users_in_memory
            form_login:
                provider: user_provider
                login_path: login
                check_path: login
            logout:
                path: /logout
    role_hierarchy: 
        ROLE_ADMIN: ROLE_USER
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER}
        - { path: ^/listar_libros, roles: ROLE_USER}
        - { path: ^/buscar, roles: ROLE_USER}
        - { path: ^/nuevo, roles: ROLE_ADMIN}
        - { path: ^/nuevo_libro, roles: ROLE_ADMIN}
    encoders:
        App\Entity\Usuario:
            algorithm: bcrypt
            cost: 12